<?php
require_once __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'application' . DIRECTORY_SEPARATOR . 'AutoLoader.php';

/**
 * Test class for AutoLoader.
 * Generated by PHPUnit on 2010-12-20 at 03:56:39.
 */
class AutoLoaderTest extends PHPUnit_Framework_TestCase {

    protected function setUp() {
        AutoLoader::instance(__DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR . 'application' . DIRECTORY_SEPARATOR)->expireCache();
        AutoLoader::instance()->saveToCache();
    }

    protected function tearDown() {
        AutoLoader::instance()->expireCache();
    }

    public function testInstance() {
        $this->assertTrue(AutoLoader::instance() instanceof AutoLoader);
        $this->assertTrue(TestClass::isLoaded());
        $this->assertTrue(TestClass2::isLoaded());
        $this->assertTrue(TestClass3::isLoaded());
    }

    public function testExpireCache() {
        $cache = file_get_contents(AutoLoader::instance()->getCacheLocation());
        $this->assertGreaterThan(0, strlen($cache));
        AutoLoader::instance()->expireCache();
        try {
            if (!$cache = file_get_contents(AutoLoader::instance()->getCacheLocation())) {
                $this->assertTrue(true);
            } else {
                $this->assertTrue(false);
            }
        } catch (Exception $ex) {
            $this->assertTrue(true);
        }
    }
}
